#index:
#    path: /
#    controller: App\Controller\DefaultController::index
book.list:
  path: '/books/list'
  controller: 'App\Controller\MrBookController::index'

book.search:
  path: '/book/search'
  controller: 'App\Controller\MrBookController::searchBooks'

mr_book_show:
  path: '/book/{id}/show'
  controller: 'App\Controller\MrBookController::show'

mr_book_edit:
  path: '/book/{id}/edit'
  controller: 'App\Controller\MrBookController::edit'

mr_book_new:
  path: '/books/new'
  controller: 'App\Controller\MrBookController::new'

mr_book_delete:
  path: '/book/{id}/delete'
  controller: 'App\Controller\MrBookController::delete'

#Leads
mr_lead_index:
  path: '/leads'
  controller: 'App\Controller\MrLeadController::index'

mr_lead_new:
  path: '/lead/new/{book}'
  controller: 'App\Controller\MrLeadController::new'

mr_lead_show:
  path: '/lead/{lead_id}'
  controller: 'App\Controller\MrLeadController::show'

mr_lead_edit:
  path: '/lead/{lead_id}/edit'
  controller: 'App\Controller\MrLeadController::edit'

mr_lead_delete:
  path: '/lead/{lead_id}/delete'
  controller: 'App\Controller\MrLeadController::delete'

# API
# Get list of has book
api.books.list:
  path: '/api/books/list'
  controller: 'App\Controller\Api\ApiBookController::list'
  methods: GET

# Get info about single book
api.books.view:
  path: '/api/book/{book_id}'
  controller: 'App\Controller\Api\ApiBookController::view'
  methods: GET
  requirements:
    book_id: '\d+'

# Search book
api.books.search:
  path: '/api/books/search'
  controller: 'App\Controller\Api\ApiBookController::searchBook'
  methods: GET

# Create new book
api.books.new:
  path: '/api/books/new'
  controller: 'App\Controller\Api\ApiBookController::new'
  methods: POST

# Delete book
api.books.delete:
  path: '/api/books/{book_id}/delete'
  controller: 'App\Controller\Api\ApiBookController::delete'
  methods: DELETE
  requirements:
    book_id: '\d+'

# API Lead
api.leads.list:
  path: '/api/leads/list'
  controller: 'App\Controller\Api\ApiLeadController::list'
  methods: GET

# Add book(s) to lead
api.leads.add:
  path: '/api/leads/add/{book_id}'
  controller: 'App\Controller\Api\ApiLeadController::add'
  #methods: GET
