#index:
#    path: /
#    controller: App\Controller\DefaultController::index
book.list:
  path: '/books/list'
  defaults:
    _controller: 'App\Controller\BookController::index'

book.search:
  path: '/book/search'
  defaults:
    _controller: 'App\Controller\BookController::searchBooks'